spring:
  application:
    name: 'order-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Manaus

# As properties abaixo agora são definidas no arquivo 'order-service-api-dev.yml' em
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_service?useSSL=false&serverTimezone=UTC
#    username: 'root'
#    password: 'root1234'
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 20000
#
#springdoc:
#  open-api:
#    info:
#      title: 'Order Service API'
#      version: '1.0.0'
#      description: 'Order Service API for managing service orders created by customers'
#server:
#  port: ${SERVER_PORT:8100}
